# Config

renderwatch:
  steps:
    telegram:
      token_plaintext: 
      token_filepath: 
      token_env_var: 

renderwatch_daemon:
  # Time (seconds) to poll the Resolve API for changes
  # Default: 2
  API_poll_time: 2