# Config

renderwatch:
  steps:
    telegram:
      token_plaintext: ''
      token_filepath: ''
      token_environment_variable_name: 'TELEGRAM_SEBNOTIFBOT_API_KEY'

renderwatch_daemon:
  # Time (seconds) to poll the Resolve API for changes
  # Default: 2
  API_poll_time: 2

  # Logging
  logs:
    # Level of logging verbosity
    level: 'normal'