version: 1
formatters:
  format_console:
    format: '%(asctime)s %(name)s %(levelname)s - %(message)s'
    datefmt: '%I:%M:%S'
  format_logfile:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: format_console
    stream: ext://sys.stdout
  logfile:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: format_logfile
    filename: logs/renderwatch.log
    when: D
    interval: 1
    backupCount: 7
    delay: True
    encoding: 'utf-8'
loggers:
  renderwatch:
    level: DEBUG
    handlers: [console, logfile]
    propagate: no
  renderwatch.events:
    level: DEBUG
    handlers: [console, logfile]
    propagate: no
root:
  level: DEBUG
  handlers: [console]